<<<<<<< Updated upstream
version: '3'
services:
  web:
    build:
    context: .
    dockerfile: Dockerfile
  ports:
=======
version: '3'
services:
  web:
    build:
    context: .
    dockerfile: Dockerfile
  ports:
>>>>>>> Stashed changes
    - "80:80"