name: Verificar Conectividade

on:
  push:
    branches:
      - main

jobs:
  check-connectivity:
    runs-on: ubuntu-22.04
    env:
     SSH_HOST: ${{ secrets.SSH_HOST }}
     SSH_USER: ${{ secrets.SSH_USER }}
     SSH_KEY: ${{ secrets.SSH_KEY }}
    steps:
      - name: Verificar conectividade com a VM
        run: |
          ssh -i $SSH_KEY $SSH_USER@$SSH_HOST ifconfig
          ping -c 4 152.67.58.233
